export const REGIONS = [
  { code: "GLOBAL", label: "🌍 Global" },
  { code: "IN", label: "🇮🇳 India" },
  { code: "US", label: "🇺🇸 USA" },
  { code: "GB", label: "🇬🇧 UK" },
  { code: "JP", label: "🇯🇵 Japan" },
  { code: "KR", label: "🇰🇷 South Korea" },
  { code: "DE", label: "🇩🇪 Germany" },
  { code: "FR", label: "🇫🇷 France" },
  { code: "AU", label: "🇦🇺 Australia" },
  { code: "BR", label: "🇧🇷 Brazil" },
  { code: "CA", label: "🇨🇦 Canada" },
  { code: "MX", label: "🇲🇽 Mexico" },
  { code: "IT", label: "🇮🇹 Italy" },
  { code: "ES", label: "🇪🇸 Spain" },
];
